/* The following code was generated by JFlex 1.5.0-SNAPSHOT */


/* --------------------------Codigo de Usuario----------------------- */
package ejemplocup;

import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\3\1\0\1\5\1\4\22\0\1\5\1\0\1\6"+
    "\5\0\1\66\1\67\1\10\1\50\1\57\1\7\1\62\1\65\12\2"+
    "\1\61\1\64\1\52\1\51\1\55\1\0\1\60\1\1\1\14\2\1"+
    "\1\23\1\25\2\1\1\11\2\1\1\24\2\1\1\32\1\31\2\1"+
    "\1\17\1\27\4\1\1\30\1\1\3\0\1\56\1\26\1\0\1\37"+
    "\1\33\1\36\1\44\1\35\1\41\1\22\1\42\1\21\1\34\1\1"+
    "\1\16\1\1\1\12\1\15\1\45\1\1\1\20\1\40\1\13\1\47"+
    "\1\43\1\46\3\1\1\53\1\0\1\54\1\63\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\1\1\5\1\6"+
    "\16\2\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\0\1\26\1\0\1\27\1\0\1\2\1\30\5\2"+
    "\1\31\4\2\1\32\1\2\1\33\5\2\1\34\3\2"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\4\2"+
    "\1\44\14\2\1\45\1\46\1\47\1\50\5\2\1\51"+
    "\1\52\1\2\1\53\1\2\1\54\2\2\1\0\3\2"+
    "\1\55\1\56\1\57\1\60\1\0\1\2\1\61\1\62"+
    "\1\0\1\2\1\0\1\63\1\64";

  private static int [] zzUnpackAction() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\70\0\340\0\u0118\0\u0150"+
    "\0\u0188\0\u01c0\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8\0\u0310"+
    "\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0"+
    "\0\u0508\0\u0540\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\70\0\70\0\u0118\0\70"+
    "\0\u0150\0\70\0\u0188\0\u0578\0\160\0\u05b0\0\u05e8\0\u0620"+
    "\0\u0658\0\u0690\0\160\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8"+
    "\0\u07e0\0\160\0\u0818\0\u0850\0\u0888\0\u08c0\0\u08f8\0\160"+
    "\0\u0930\0\u0968\0\u09a0\0\70\0\70\0\70\0\70\0\160"+
    "\0\160\0\160\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\160\0\u0ab8"+
    "\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78"+
    "\0\u0cb0\0\u0ce8\0\u0d20\0\160\0\160\0\160\0\160\0\u0d58"+
    "\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\160\0\160\0\u0e70\0\160"+
    "\0\u0ea8\0\160\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8"+
    "\0\160\0\160\0\160\0\160\0\u1030\0\u1068\0\160\0\160"+
    "\0\u10a0\0\u10d8\0\u1110\0\160\0\70";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\3\1\21\4\3\1\2\3\3\1\22\2\3\1\23"+
    "\1\24\2\3\1\25\3\3\1\26\1\27\1\3\1\30"+
    "\1\31\1\32\1\33\1\34\1\2\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\71\0"+
    "\2\3\6\0\15\3\1\0\21\3\22\0\1\4\70\0"+
    "\1\5\65\0\5\47\1\50\2\0\15\47\1\0\21\47"+
    "\21\0\5\51\1\0\1\52\1\0\15\51\1\0\21\51"+
    "\21\0\5\53\2\0\1\52\15\53\1\0\21\53\21\0"+
    "\2\3\6\0\1\3\1\54\13\3\1\0\3\3\1\55"+
    "\15\3\21\0\2\3\6\0\4\3\1\56\10\3\1\0"+
    "\6\3\1\57\12\3\21\0\2\3\6\0\7\3\1\60"+
    "\5\3\1\0\13\3\1\61\5\3\21\0\2\3\6\0"+
    "\4\3\1\62\10\3\1\0\21\3\21\0\2\3\6\0"+
    "\15\3\1\0\12\3\1\63\6\3\21\0\2\3\6\0"+
    "\4\3\1\64\10\3\1\0\6\3\1\65\12\3\21\0"+
    "\2\3\6\0\2\3\1\66\7\3\1\67\2\3\1\0"+
    "\21\3\21\0\2\3\6\0\1\3\1\70\13\3\1\0"+
    "\11\3\1\71\1\72\6\3\21\0\2\3\6\0\15\3"+
    "\1\0\4\3\1\73\14\3\21\0\2\3\6\0\5\3"+
    "\1\74\7\3\1\0\11\3\1\75\7\3\21\0\2\3"+
    "\6\0\5\3\1\76\7\3\1\0\10\3\1\77\10\3"+
    "\21\0\2\3\6\0\10\3\1\100\4\3\1\0\10\3"+
    "\1\101\10\3\21\0\2\3\6\0\4\3\1\102\10\3"+
    "\1\0\21\3\21\0\2\3\6\0\15\3\1\0\13\3"+
    "\1\103\5\3\71\0\1\104\73\0\1\105\21\0\1\106"+
    "\41\0\1\107\17\0\2\3\6\0\2\3\1\110\12\3"+
    "\1\0\21\3\21\0\2\3\6\0\2\3\1\111\12\3"+
    "\1\0\21\3\21\0\2\3\6\0\15\3\1\0\17\3"+
    "\1\112\1\3\21\0\2\3\6\0\15\3\1\0\20\3"+
    "\1\113\21\0\2\3\6\0\15\3\1\0\6\3\1\114"+
    "\12\3\21\0\2\3\6\0\4\3\1\115\10\3\1\0"+
    "\21\3\21\0\2\3\6\0\4\3\1\116\10\3\1\0"+
    "\21\3\21\0\2\3\6\0\2\3\1\117\12\3\1\0"+
    "\21\3\21\0\2\3\6\0\7\3\1\120\5\3\1\0"+
    "\21\3\21\0\2\3\6\0\13\3\1\121\1\3\1\0"+
    "\21\3\21\0\2\3\6\0\15\3\1\0\13\3\1\122"+
    "\5\3\21\0\2\3\6\0\15\3\1\0\14\3\1\123"+
    "\4\3\21\0\2\3\6\0\15\3\1\0\5\3\1\124"+
    "\13\3\21\0\2\3\6\0\15\3\1\0\11\3\1\125"+
    "\7\3\21\0\2\3\6\0\15\3\1\0\10\3\1\126"+
    "\10\3\21\0\2\3\6\0\15\3\1\0\10\3\1\127"+
    "\10\3\21\0\2\3\6\0\15\3\1\0\11\3\1\130"+
    "\7\3\21\0\2\3\6\0\5\3\1\131\7\3\1\0"+
    "\21\3\21\0\2\3\6\0\4\3\1\132\10\3\1\0"+
    "\21\3\21\0\2\3\6\0\10\3\1\133\4\3\1\0"+
    "\21\3\21\0\2\3\6\0\15\3\1\0\6\3\1\134"+
    "\12\3\21\0\2\3\6\0\1\3\1\135\13\3\1\0"+
    "\21\3\21\0\2\3\6\0\5\3\1\136\7\3\1\0"+
    "\21\3\21\0\2\3\6\0\15\3\1\0\16\3\1\137"+
    "\2\3\21\0\2\3\6\0\10\3\1\140\4\3\1\0"+
    "\21\3\21\0\2\3\6\0\14\3\1\141\1\0\21\3"+
    "\21\0\2\3\6\0\15\3\1\0\6\3\1\142\12\3"+
    "\21\0\2\3\6\0\4\3\1\143\10\3\1\0\21\3"+
    "\21\0\2\3\6\0\15\3\1\0\6\3\1\144\12\3"+
    "\21\0\2\3\6\0\15\3\1\0\6\3\1\145\12\3"+
    "\21\0\2\3\6\0\15\3\1\0\7\3\1\146\11\3"+
    "\21\0\2\3\6\0\15\3\1\0\11\3\1\147\7\3"+
    "\21\0\2\3\6\0\15\3\1\0\6\3\1\150\12\3"+
    "\21\0\2\3\6\0\15\3\1\0\11\3\1\151\7\3"+
    "\21\0\2\3\6\0\5\3\1\152\7\3\1\0\21\3"+
    "\21\0\2\3\6\0\5\3\1\153\7\3\1\0\21\3"+
    "\21\0\2\3\6\0\1\3\1\154\13\3\1\0\21\3"+
    "\21\0\2\3\6\0\15\3\1\155\21\3\21\0\2\3"+
    "\6\0\7\3\1\156\5\3\1\0\21\3\21\0\2\3"+
    "\6\0\10\3\1\157\4\3\1\0\21\3\21\0\2\3"+
    "\6\0\15\3\1\0\7\3\1\160\11\3\21\0\2\3"+
    "\6\0\15\3\1\0\11\3\1\161\7\3\21\0\2\3"+
    "\6\0\15\3\1\0\6\3\1\162\12\3\21\0\2\3"+
    "\6\0\15\3\1\0\6\3\1\163\12\3\21\0\2\3"+
    "\6\0\11\3\1\164\3\3\1\0\21\3\47\0\1\165"+
    "\41\0\2\3\6\0\10\3\1\166\4\3\1\0\21\3"+
    "\21\0\2\3\6\0\15\3\1\0\15\3\1\167\3\3"+
    "\21\0\2\3\6\0\2\3\1\170\12\3\1\0\21\3"+
    "\50\0\1\171\40\0\2\3\6\0\2\3\1\172\12\3"+
    "\1\0\21\3\51\0\1\173\37\0\2\3\6\0\15\3"+
    "\1\0\11\3\1\174\7\3\43\0\1\175\44\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4424];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\25\1\14\11\1\0\1\11"+
    "\1\0\1\11\1\0\30\1\4\11\45\1\1\0\7\1"+
    "\1\0\3\1\1\0\1\1\1\0\1\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[125];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /*  Generamos un java_cup.Symbol para guardar el tipo de token 
        encontrado */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado 
       junto con su valor */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new Error("Caracter ilegal <"+yytext()+">");
          }
        case 53: break;
        case 2: 
          { System.out.print(yytext()); 
                      return symbol(sym.IDENTIFICADOR, new String(yytext()));
          }
        case 54: break;
        case 3: 
          { System.out.print(yytext()); 
                      return symbol(sym.ENTERO, new String(yytext()));
          }
        case 55: break;
        case 4: 
          { /* ignora el espacio */
          }
        case 56: break;
        case 5: 
          { System.out.print(" - "); return symbol(sym.OP_RESTA);
          }
        case 57: break;
        case 6: 
          { System.out.print(" * "); return symbol(sym.OP_MULT);
          }
        case 58: break;
        case 7: 
          { System.out.print(" + "); return symbol(sym.OP_SUMA);
          }
        case 59: break;
        case 8: 
          { System.out.print(" = "); return symbol(sym.OP_IGUAL);
          }
        case 60: break;
        case 9: 
          { System.out.print(" < "); return symbol(sym.OP_MENORQ);
          }
        case 61: break;
        case 10: 
          { System.out.print(" { "); return symbol(sym.CBLEFT);
          }
        case 62: break;
        case 11: 
          { System.out.print(" } "); return symbol(sym.CBRIGHT);
          }
        case 63: break;
        case 12: 
          { System.out.print(" ^ "); return symbol(sym.OP_POW);
          }
        case 64: break;
        case 13: 
          { System.out.print(" , "); return symbol(sym.COMA);
          }
        case 65: break;
        case 14: 
          { System.out.print(" @ "); return symbol(sym.ARROBA);
          }
        case 66: break;
        case 15: 
          { System.out.print(" : "); return symbol(sym.TWO_POINTS);
          }
        case 67: break;
        case 16: 
          { System.out.print(" . "); return symbol(sym.POINT);
          }
        case 68: break;
        case 17: 
          { System.out.print(" ~ "); return symbol(sym.NEGATION);
          }
        case 69: break;
        case 18: 
          { System.out.print(" ; "); return symbol(sym.SEMI);
          }
        case 70: break;
        case 19: 
          { System.out.print(" / "); return symbol(sym.OP_DIV);
          }
        case 71: break;
        case 20: 
          { System.out.print(" ( "); return symbol(sym.PARENIZQ);
          }
        case 72: break;
        case 21: 
          { System.out.print(" ) "); return symbol(sym.PARENDER);
          }
        case 73: break;
        case 22: 
          { System.out.print(yytext()); 
                      return symbol(sym.CADENA, new String(yytext()));
          }
        case 74: break;
        case 23: 
          { 
          }
        case 75: break;
        case 24: 
          { System.out.print(" IO "); return symbol(sym.TIPO_IO);
          }
        case 76: break;
        case 25: 
          { System.out.print(" of "); return symbol(sym.OF);
          }
        case 77: break;
        case 26: 
          { System.out.print(" in "); return symbol(sym.IN);
          }
        case 78: break;
        case 27: 
          { System.out.print(" if "); return symbol(sym.IF);
          }
        case 79: break;
        case 28: 
          { System.out.print(" fi "); return symbol(sym.FI);
          }
        case 80: break;
        case 29: 
          { System.out.print(" += "); return symbol(sym.OP_SUMAIGUAL);
          }
        case 81: break;
        case 30: 
          { System.out.print(" => "); return symbol(sym.RIGHT_ALLOC);
          }
        case 82: break;
        case 31: 
          { System.out.print(" <- "); return symbol(sym.LEFT_ALLOC);
          }
        case 83: break;
        case 32: 
          { System.out.print(" <= "); return symbol(sym.OP_MENORIGUALQ);
          }
        case 84: break;
        case 33: 
          { System.out.print(" Int "); return symbol(sym.TIPO_INT);
          }
        case 85: break;
        case 34: 
          { System.out.print(" not "); return symbol(sym.NOT);
          }
        case 86: break;
        case 35: 
          { System.out.print(" new "); return symbol(sym.NEW);
          }
        case 87: break;
        case 36: 
          { System.out.print(" let "); return symbol(sym.LET);
          }
        case 88: break;
        case 37: 
          { System.out.print(" true "); return symbol(sym.BOOLEAN_TRUE);
          }
        case 89: break;
        case 38: 
          { System.out.print(" then "); return symbol(sym.THEN);
          }
        case 90: break;
        case 39: 
          { System.out.print(" Bool "); return symbol(sym.TIPO_BOOL);
          }
        case 91: break;
        case 40: 
          { System.out.print(" loop "); return symbol(sym.LOOP);
          }
        case 92: break;
        case 41: 
          { System.out.print(" else "); return symbol(sym.ELSE);
          }
        case 93: break;
        case 42: 
          { System.out.print(" esac "); return symbol(sym.ESAC);
          }
        case 94: break;
        case 43: 
          { System.out.print(" case "); return symbol(sym.CASE);
          }
        case 95: break;
        case 44: 
          { System.out.print(" pool "); return symbol(sym.POOL);
          }
        case 96: break;
        case 45: 
          { System.out.print(" class "); return symbol(sym.CLASS);
          }
        case 97: break;
        case 46: 
          { System.out.print(" false "); return symbol(sym.BOOLEAN_FALSE);
          }
        case 98: break;
        case 47: 
          { System.out.print(" while "); return symbol(sym.WHILE);
          }
        case 99: break;
        case 48: 
          { System.out.print(" String "); return symbol(sym.TIPO_STRING);
          }
        case 100: break;
        case 49: 
          { System.out.print(" isvoid "); return symbol(sym.ISVOID);
          }
        case 101: break;
        case 50: 
          { System.out.print(" TIPO_OBJECT "); return symbol(sym.TIPO_OBJECT);
          }
        case 102: break;
        case 51: 
          { System.out.print(" inherits "); return symbol(sym.INHERITS);
          }
        case 103: break;
        case 52: 
          { System.out.print(" SELF_TYPE "); return symbol(sym.SELF_TYPE);
          }
        case 104: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
