
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 04 00:52:58 CDT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFT_ALLOC = 35;
  public static final int INHERITS = 19;
  public static final int POOL = 22;
  public static final int ENTERO = 45;
  public static final int CBRIGHT = 37;
  public static final int CASE = 25;
  public static final int BOOLEAN_TRUE = 30;
  public static final int PARENIZQ = 7;
  public static final int SEMI = 2;
  public static final int TIPO_STRING = 11;
  public static final int RIGHT_ALLOC = 38;
  public static final int TWO_POINTS = 43;
  public static final int OP_MENORQ = 33;
  public static final int OP_SUMAIGUAL = 31;
  public static final int OP_DIV = 6;
  public static final int IDENTIFICADOR = 47;
  public static final int NOT = 29;
  public static final int IN = 15;
  public static final int ARROBA = 41;
  public static final int CLASS = 13;
  public static final int FI = 16;
  public static final int OP_MENORIGUALQ = 34;
  public static final int SELF_TYPE = 12;
  public static final int LOOP = 21;
  public static final int OF = 28;
  public static final int EOF = 0;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int NEGATION = 42;
  public static final int COMA = 40;
  public static final int CADENA = 46;
  public static final int OP_MULT = 5;
  public static final int ISVOID = 18;
  public static final int OP_RESTA = 4;
  public static final int PARENDER = 8;
  public static final int TIPO_INT = 9;
  public static final int BOOLEAN_FALSE = 17;
  public static final int ELSE = 14;
  public static final int OP_IGUAL = 32;
  public static final int POINT = 44;
  public static final int WHILE = 24;
  public static final int ESAC = 26;
  public static final int LET = 20;
  public static final int THEN = 23;
  public static final int TIPO_BOOL = 10;
  public static final int OP_SUMA = 3;
  public static final int OP_POW = 39;
  public static final int CBLEFT = 36;
}

