
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 05 11:46:17 CDT 2015
//----------------------------------------------------

package ejemplocup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFT_ALLOC = 37;
  public static final int COMENTARIOUNO = 2;
  public static final int INHERITS = 21;
  public static final int POOL = 24;
  public static final int ENTERO = 51;
  public static final int CBRIGHT = 39;
  public static final int CASE = 27;
  public static final int BOOLEAN_TRUE = 32;
  public static final int PARENIZQ = 9;
  public static final int SEMI = 4;
  public static final int TIPO_STRING = 13;
  public static final int RIGHT_ALLOC = 40;
  public static final int TWO_POINTS = 45;
  public static final int OP_MENORQ = 35;
  public static final int OP_SUMAIGUAL = 33;
  public static final int OP_DIV = 8;
  public static final int IDENTIFICADOR = 53;
  public static final int NOT = 31;
  public static final int IN = 17;
  public static final int ESPACIO = 47;
  public static final int ARROBA = 43;
  public static final int CLASS = 15;
  public static final int FI = 18;
  public static final int OP_MENORIGUALQ = 36;
  public static final int SELF_TYPE = 14;
  public static final int LOOP = 23;
  public static final int IF = 48;
  public static final int OF = 30;
  public static final int EOF = 0;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int NEGATION = 44;
  public static final int COMA = 42;
  public static final int CADENA = 52;
  public static final int OP_MULT = 7;
  public static final int ISVOID = 20;
  public static final int OP_RESTA = 6;
  public static final int PARENDER = 10;
  public static final int TIPO_INT = 11;
  public static final int COMENTARIODOS = 3;
  public static final int TIPO_OBJECT = 50;
  public static final int BOOLEAN_FALSE = 19;
  public static final int ELSE = 16;
  public static final int OP_IGUAL = 34;
  public static final int POINT = 46;
  public static final int TIPO_IO = 49;
  public static final int WHILE = 26;
  public static final int ESAC = 28;
  public static final int LET = 22;
  public static final int THEN = 25;
  public static final int TIPO_BOOL = 12;
  public static final int OP_SUMA = 5;
  public static final int OP_POW = 41;
  public static final int CBLEFT = 38;
}

